"""empty message

Revision ID: 4f590215d3f0
Revises: None
Create Date: 2016-11-03 03:34:10.718281

"""

# revision identifiers, used by Alembic.
revision = '4f590215d3f0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imei', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('serial', sa.Integer(), nullable=True),
    sa.Column('sim', sa.Integer(), nullable=True),
    sa.Column('realm', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device')
    ### end Alembic commands ###
